version: '3'

vars:
  APPS:
    sh: ls cmd

tasks:
  default:
    cmds:
      - task --list

  # ── per-app ──────────────────────────────────────────────────────────────

  'build:*':
    desc: "Build one app: `task build:<name>`"
    label: 'build-{{index .MATCH 0}}'
    sources:
      - cmd/{{index .MATCH 0}}/**/*.go
      - cmd/{{index .MATCH 0}}/go.*
      - internal/service/{{index .MATCH 0}}/**/*.go
      - internal/pkg/**/*.go
    generates:
      - bin/{{index .MATCH 0}}
    cmds:
      - mkdir -p {{.ROOT_DIR}}/bin
      - go build -ldflags='-s -w' -trimpath -o {{.ROOT_DIR}}/bin/{{index .MATCH 0}} ./cmd/{{index .MATCH 0}}

  'docker:*':
    desc: "Build Docker image for one app: `task docker:<name>`"
    cmds:
      - docker build --build-arg APP={{index .MATCH 0}} -t {{index .MATCH 0}} .

  'run:*':
    desc: "Run one app: `task run:<name>`"
    cmds:
      - go run ./cmd/{{index .MATCH 0}}

  'test:*':
    desc: "Test one app: `task test:<name>`"
    cmds:
      - go test ./internal/service/{{index .MATCH 0}}/...  ./cmd/{{index .MATCH 0}} -race

  # ── global ─────────────────────────────────────────────────────────────

  build:
    desc: Build all apps
    cmds:
      - for: { var: APPS }
        task: 'build:{{.ITEM}}'

  test:
    desc: Test
    cmds:
      - go test ./... -race

  lint:
    desc: Lint
    cmds:
      - golangci-lint run --config {{.ROOT_DIR}}/.golangci.yaml ./...

  tidy:
    desc: go mod tidy .
    cmds:
      - go mod tidy
      - for: { var: APPS }
        cmd: go -C cmd/{{.ITEM}} mod tidy
      - go work sync

  generate:
    desc: go generate.
    cmds:
      - go generate ./...
